nome = input("Digite seu nome: ")
sobrenome = input("Digite o sobrenome: ")
curso = input("Digite seu curso: ")
cidade = input("Digite sua cidade: ")
idade = int(input("Digite sua idade: "))

print("\n========== CADASTRO DO ALUNO ==========")
print(f"Aluno(a): {nome} {sobrenome}")
print(f"Idade: {idade} anos")
print(f"Cidade: {cidade}")
print(f"Curso: {curso}")