nome = input("Digite seu nome: ")
sobrenome = str(input("Digite o sobrenome: "))
curso = input("Digite seu curso: ")
cidade = input("Digite sua cidade: ")
print(f"{nome} {sobrenome} {curso} {cidade}")
